apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: broken-

bases:
  - https://github.com/kubernetes-sigs/kustomize/examples/helloWorld

patchesStrategicMerge:
  - patch.yaml