apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: docker-registry-key
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=secrets/docker-registry-key

bases:
  - broken-app
  - working-app